name: upload-event
description: ""

runs:
  using: "composite"
  
  steps:
  - name: Upload
    uses: actions/upload-artifact@v4
    with:
      name: test-event-file
      path: ${{ github.event_path }}
      retention-days: 1