name: Publish Test Results

on:
  workflow_run:
    workflows: ["build", "Build + Test"]
    types: [completed]
permissions: {}

jobs:
  publish-test-results:
    if: github.event.workflow_run.conclusion != 'skipped'
    runs-on: ubuntu-latest
    name: Publish test results
    permissions:
      checks: write
      pull-requests: write
      actions: read
    steps:

    - name: Download event file
      uses: actions/download-artifact@v4
      with:
        run_id: ${{ github.event.workflow_run.id }}
        name: test-event-file

    - name: Download test results
      uses: actions/download-artifact@v4
      with:
        run_id: ${{ github.event.workflow_run.id }}
        pattern: test-results *
        merge-multiple: false

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        commit: ${{ github.event.workflow_run.head_sha }}
        event_file: event.json
        event_name: ${{ github.event.workflow_run.event }}

        files: '**/*.trx'
        comment_mode: ${{ (github.event.workflow_run.event == 'pull_request' || github.event_name == 'pull_request') && 'failures' || 'off' }}
        report_individual_runs: true
